# Generated by Django 2.2.4 on 2020-08-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcontrollerconfig',
            name='county',
            field=models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='script.County'),
        ),
    ]
