# Generated by Django 2.2.4 on 2020-08-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20200820_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcontroller',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadControllerConfig'),
        ),
    ]
