# Generated by Django 2.2.4 on 2020-08-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_auto_20200820_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charginginterval',
            name='session',
            field=models.ForeignKey(db_column='session', on_delete=django.db.models.deletion.CASCADE, to='script.ChargingSession'),
        ),
        migrations.AlterField(
            model_name='chargingport',
            name='station',
            field=models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='script.ChargingStation'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='script.Driver'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='zipcode',
            field=models.ForeignKey(db_column='zipcode', on_delete=django.db.models.deletion.CASCADE, to='script.ZipCode'),
        ),
        migrations.AlterField(
            model_name='costbenefit',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.CostBenefitConfig'),
        ),
        migrations.AlterField(
            model_name='costbenefitconfig',
            name='lf_config',
            field=models.ForeignKey(db_column='lf_config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='zipcode',
            field=models.ForeignKey(db_column='zipcode', on_delete=django.db.models.deletion.CASCADE, to='script.ZipCode'),
        ),
        migrations.AlterField(
            model_name='emission',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.EmissionConfig'),
        ),
        migrations.AlterField(
            model_name='emissionconfig',
            name='lf_config',
            field=models.ForeignKey(db_column='lf_config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='county',
            field=models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='script.County'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.GasConsumptionConfig'),
        ),
        migrations.AlterField(
            model_name='gasconsumptionconfig',
            name='lf_config',
            field=models.ForeignKey(db_column='lf_config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='loadforecast',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='loadprofile',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadProfileConfig'),
        ),
        migrations.AlterField(
            model_name='loadprofileconfig',
            name='lf_config',
            field=models.ForeignKey(db_column='lf_config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='netpresentvalue',
            name='config',
            field=models.ForeignKey(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='script.NetPresentValueConfig'),
        ),
        migrations.AlterField(
            model_name='netpresentvalueconfig',
            name='lf_config',
            field=models.ForeignKey(db_column='lf_config', on_delete=django.db.models.deletion.CASCADE, to='script.LoadForecastConfig'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='county',
            field=models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='script.County'),
        ),
    ]
