# Generated by Django 2.2.4 on 2020-09-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_auto_20200820_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costbenefit',
            old_name='cost_benefit',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='emission',
            old_name='emissions',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='gasconsumption',
            old_name='consumption',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='loadprofile',
            old_name='loads',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='netpresentvalue',
            old_name='npv',
            new_name='values',
        ),
    ]
